# Generated by Django 5.0.4 on 2024-04-26 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_name', models.CharField(max_length=100)),
                ('train_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('origin_station', models.CharField(max_length=100)),
                ('sleeper_seats', models.PositiveIntegerField(default=0)),
                ('ac3_seats', models.PositiveIntegerField(default=0)),
                ('ac2_seats', models.PositiveIntegerField(default=0)),
                ('ac1_seats', models.PositiveIntegerField(default=0)),
                ('sleeper_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ac3_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ac2_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ac1_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticketdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('train_no', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('origin_station', models.CharField(max_length=100)),
                ('train_class', models.CharField(max_length=50)),
                ('copassengers', models.CharField(max_length=255)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('head', models.CharField(max_length=100)),
                ('passage', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('train_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
