# Generated by Django 5.0.4 on 2024-04-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketghar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('train_no', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('origin_station', models.CharField(max_length=100)),
                ('train_class', models.CharField(max_length=50)),
                ('copassengers', models.CharField(max_length=255)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('head', models.CharField(max_length=100)),
                ('passage', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('train_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticketdata',
        ),
    ]
